### ISSUE TITLE
Expand "Using WebAssembly" chapter

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#12]
Ref https://github.com/denoland/deno/issues/6844

- [ ] Link to MDN sources
- [ ] Provide Rust program that compiles to provided bytes
- [ ] Provide examples using `WebAssembly.instantiateStreaming` and `WebAssembly.compileStreaming`

Mentioned in the recent 1.12 blog post: https://deno.com/blog/v1.12#streaming-instantiation-and-async-compilation-support-for-webassembly

**Comment by GJZwiers** [comment]
I'd like to contribute to this chapter but I have some questions:

- What should the scope of the chapter be? That is, should it only cover how to use wasm modules in Deno
or how to write wasm modules as well? I'm asking because there are already many good resources for the latter on for example MDN and the Rust docs. I think a lot of other content in the chapter would depend on this choice. For example, I could write a page that shows how to write some Rust, use `wasm-bindgen` to make type bindings and create a module with `wasm-pack` that can be run in Deno, although most of that page would be similar to what's on MDN.

- On the same note as the first question. should there be a page on optimizing wasm for speed and/or size or should the chapter just link to existing guides on the web for that?

- Should there be a page with a list of helpful resources, maybe with links to for example the `web-sys` Rust crate, `wasm-bindgen` docs, and so on?

I'm curious to hear what you think :) Personally, I'd like having some pages that are tailored to Deno + WebAssembly as a lot of tutorials on the web assume Node/npm/Webpack or something along those lines.

**Comment by bartlomieju** [comment]
> I'd like to contribute to this chapter but I have some questions:

Thanks!

> 
> * What should the scope of the chapter be? That is, should it only cover how to use wasm modules in Deno
>   or how to write wasm modules as well? I'm asking because there are already many good resources for the latter on for example MDN and the Rust docs. I think a lot of other content in the chapter would depend on this choice. For example, I could write a page that shows how to write some Rust, use `wasm-bindgen` to make type bindings and create a module with `wasm-pack` that can be run in Deno, although most of that page would be similar to what's on MDN.

It should cover how to use WASM modules in Deno. We don't want to repeat (and later maintain) general guides how to write WASM, instead we should link do MDN and other high quality resources on the topic.

> * On the same note as the first question. should there be a page on optimizing wasm for speed and/or size or should the chapter just link to existing guides on the web for that?

It should link to existing guides.

> * Should there be a page with a list of helpful resources, maybe with links to for example the `web-sys` Rust crate, `wasm-bindgen` docs, and so on?
> 

Sure, such list would be helpful.

> I'm curious to hear what you think :) Personally, I'd like having some pages that are tailored to Deno + WebAssembly as a lot of tutorials on the web assume Node/npm/Webpack or something along those lines.

Having Deno + WebAssembly tutorials would be great, to fill the gap.

**Comment by GJZwiers** [comment]
I've made a PR for the issue: #71

**Comment by bartlomieju** [comment]
Done in #51
