### ISSUE TITLE
Style Guide History

### ISSUE THREAD

**Issue by shellscape** [denoland/manual#154]
Howdy 👋  I was reading up on Deno, as it's something that we're looking to add to our toolchain, and I happened across a few issues talking about naming formats for the registry, and one that referenced the style guide. Given that many (most?) Deno users are Node converts or current users, I found the assertion that snake_cased filenames were considered best practice very curious (https://deno.land/manual/contributing/style_guide#use-underscores-not-dashes-in-filenames). It's something we see in other non-JS language quite often, but it was the first time I'd seen that in something node-adjacent that wasn't authored by python devs.

So I figured there must be a reason, and being open source, some kind of reference, decision making history, or discussion history as to why the decision was made. Being able to tell my team that it's not something that a lone developer decided for arbitrary or personal preferences is pretty important for buy-in. Unfortunately the history for the file in this repo doesn't contain any breadcrumbs that allow for tracing the decision making process for that bit. I thought that was unfortunate.

Can anyone point me in the right direction?

**Comment by kitsonk** [comment]
Style guides are often full of arbitrary decisions.

It should be made clear, that the style guide referenced is for contributing _code to Deno_, not in any way a suggestion of the style end users may want to adopt.  Styles enforced by `deno lint` are based on what are generally accepted as "good practice" and generally follow eslint recommended styles.  File naming is not one that `deno lint` covers.

In this case, again only for contributing code to Deno, it is because of the convention in Rust for naming modules, in order to have consistency between how the Rust modules and files are named and how internal Deno (or `std` library) modules are named.

**Comment by shellscape** [comment]
Solid info. Thank you for sharing and clarifying.
