### ISSUE TITLE
Add examples of using hashbangs

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#161]
There's not a single example of using shebangs to make Deno scripts executable.

There should be an example showing how to add a hashbang:
```
#!/usr/bin/env -S deno run --unstable --allow-write --allow-read --allow-run
```

We might link to some executable scripts from Deno repo like:
- https://github.com/denoland/deno/blob/28dbb4a95e569772600ae28ae4fe8b6fa2a4d2af/tools/lint.js
- https://github.com/denoland/deno/blob/28dbb4a95e569772600ae28ae4fe8b6fa2a4d2af/tools/format.js

**Comment by KyleJune** [comment]
When I tried using that hash bang in the denoland/deno:alpine-1.16.1 image I got the following error. I ended up switching to using the default denoland/deno image instead of alpine. I think it would be good to include in the manual an example of using hashbangs for each OS deno has a docker image for.

https://hub.docker.com/r/denoland/deno

```
/usr/bin/env: unrecognized option: S
BusyBox v1.32.1 () multi-call binary.

Usage: env [-iu] [-] [name=value]... [PROG ARGS]

Print the current environment or run PROG after setting up
the specified environment

        -, -i   Start with an empty environment
        -u      Remove variable from the environment
```

**Comment by AnInternetTroll** [comment]
An example about using shebangs has been added https://deno.land/manual/examples/shebang#example

In KyleJune's case the -S option didn't work because alpine linux uses busybox by default, which does not support the -S flag https://www.busybox.net/downloads/BusyBox.html#env

Other notable operating systems that don't support -S flag are [OpenBSD](https://man.openbsd.org/env) and [NetBSD](https://man.netbsd.org/env.1), as well as any strictly POSIX compliant operating systems https://www.unix.com/man-page/posix/1P/env/, though afaik deno doesn't run on those anyway.

**Comment by kt3k** [comment]
Closing this for now.

@AnInternetTroll Thanks for the input. We need to address `-S` issue when we officially support any of those OSes
